# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='parent_profile_pictures'),
        ),
    ]
