# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_remove_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('parent', 'parent user'), ('teacher', 'teacher user'), ('admin', 'admin user')], default='parent', max_length=7),
        ),
    ]
