# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0005_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='parent_profile_pictures'),
        ),
    ]
