# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0006_parent_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='picture_url',
            field=models.URLField(default='http://res.cloudinary.com/dpkceqvfi/image/upload/v1450429700/default_profile_ru96fo.png'),
        ),
    ]
