# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='school_class',
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
    ]
