# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_classevent_schoolevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('charge_id', models.CharField(max_length=255, null=True)),
                ('refunded', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='class_fee_images')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.SchoolClass')),
                ('student', models.ManyToManyField(to='schools.Student')),
            ],
        ),
    ]
