# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_classfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classfee',
            name='student',
        ),
    ]
