# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20151211_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeepayment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
