# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_classfeepayment_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfeepayment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
