# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_classhomework_studenthomework'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthomework',
            name='turned_in',
            field=models.DateField(null=True),
        ),
    ]
