# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_studenthomework_turned_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeepayment',
            name='amount_needed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
