# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_auto_20151216_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='class_forms/%Y/%m/%d')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.SchoolClass')),
            ],
        ),
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_forms/%Y/%m/%d')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.TextField(default='subject goes here')),
                ('message', models.TextField(default='message goes here')),
                ('signer', models.CharField(max_length=255)),
                ('viewed', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('class_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.ClassForm')),
            ],
        ),
    ]
