# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_classform_studentform'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.Student'),
        ),
    ]
