# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 21:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_studentform_due_date'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='studentform',
    #         name='signer',
    #         field=django.contrib.postgres.fields.jsonb.JSONField(),
    #     ),
    # ]
