# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_auto_20151217_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='signer',
            field=models.CharField(max_length=255),
        ),
    ]
