# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_auto_20151217_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentform',
            name='class_form',
        ),
        migrations.RemoveField(
            model_name='studentform',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentForm',
        ),
    ]
