# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_studentform'),
    ]

    operations = [
        migrations.AddField(
            model_name='classevent',
            name='picture_url',
            field=models.URLField(default='http://res.cloudinary.com/dpkceqvfi/image/upload/v1450429700/default_profile_ru96fo.png'),
        ),
        migrations.AddField(
            model_name='classfee',
            name='picture_url',
            field=models.URLField(default='http://res.cloudinary.com/dpkceqvfi/image/upload/v1450429700/default_profile_ru96fo.png'),
        ),
        migrations.AddField(
            model_name='classfeepayment',
            name='picture_url',
            field=models.URLField(default='http://res.cloudinary.com/dpkceqvfi/image/upload/v1450429700/default_profile_ru96fo.png'),
        ),
        migrations.AddField(
            model_name='classhomework',
            name='picture_url',
            field=models.URLField(default='http://res.cloudinary.com/dpkceqvfi/image/upload/v1450429700/default_profile_ru96fo.png'),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='picture_url',
            field=models.URLField(default='http://res.cloudinary.com/dpkceqvfi/image/upload/v1450429700/default_profile_ru96fo.png'),
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='picture_url',
            field=models.URLField(default='http://res.cloudinary.com/dpkceqvfi/image/upload/v1450429700/default_profile_ru96fo.png'),
        ),
    ]
