# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_auto_20151218_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='classhomework',
            name='file',
            field=models.FileField(null=True, upload_to='class_homework/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='file',
            field=models.FileField(null=True, upload_to='student_homework/%Y/%m/%d'),
        ),
    ]
