# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_auto_20151220_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthomework',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
