# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0022_studenthomework_total_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHomeworkGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='F', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('student_homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schools.StudentHomework')),
            ],
        ),
    ]
