# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_studenthomeworkgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthomework',
            name='grade',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
