# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0026_studentattendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='school_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.SchoolClass'),
        ),
    ]
