# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0029_auto_20151230_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='school_class',
        ),
    ]
