# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 04:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0031_studentattendance_school_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('good_behavior', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.SchoolClass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Student')),
            ],
        ),
    ]
