# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0033_auto_20160101_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomework',
            name='grade',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
