# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 08:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0036_auto_20160104_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfee',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
