# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 05:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0037_auto_20160104_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomework',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
