# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0040_auto_20160105_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='sign_url',
            field=models.URLField(default='http://res.cloudinary.com/dpkceqvfi/image/upload/v1450429700/default_profile_ru96fo.png'),
        ),
    ]
