# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0041_studentform_sign_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='sign_url',
            field=models.URLField(null=True),
        ),
    ]
