# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0042_auto_20160106_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture_url',
            field=models.URLField(default='http://res.cloudinary.com/dpkceqvfi/image/upload/v1450429700/default_profile_ru96fo.png'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile_pictures'),
        ),
    ]
